### ISSUE TITLE
关于这个项目的一些想法

### ISSUE THREAD

**Issue by DanielZhao1990** [liuguangqiang/Idaily#8]
首先感谢作者提供这个demo.以下是个人在学习过程中的感受。
1. 这确实是个demo，简单的demo。
2. 作者用了一堆当前最流行的框架和架构，但是也只是用了。项目的结构依然不够清晰，Dagger2的使用，并没有体现出dagger的优势，许多该用的地方貌似没有用到dagger。感觉作者其实对于整体项目是没有一个清晰架构的。只是在写demo时拼起来的。mvvm也没有看到我理解的mvvm的样子。
如果能够完善了，就太好了。可惜个人能力不足。无法贡献。。
个人之见，说错的地方，表示歉意。

**Comment by liuguangqiang** [comment]
确实如此，dagger和mvvm我也是才开始用，学着用，我对他们的理解，也只是停留在用的层面上，没有理解其精髓，后面如果有更多的理解和想法，我肯定也会加入到这个项目中的，多谢你的意见哈，当然，如果能有pull requests的话，我会更感谢的
